[package]
name = "elast-site"
version = "0.1.0"
authors = ["Ede Meijer <ede@elastict.nl"]
edition = "2018"

[dependencies]
rocket = "0.4.2"

[dependencies.rocket_contrib]
version = "0.4.2"
features = ["tera_templates"]
